### ISSUE TITLE
error with common.smk

### ISSUE THREAD

**Issue by anjanaanilkumar1289** [snakemake-workflows/dna-seq-gatk-variant-calling#4] opened 2019-01-21 11:41 UTC
I am getting error from line 10 in https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/blob/master/rules/common.smk

line 10 samples = pd.read_table(config["samples"]).set_index("sample", drop=False)

TypeError: string indices must be integers

Can you please help me to fix the error.

**Comment by johanneskoester** [comment] 2019-01-29 09:49
Can you show me your config file? Did you change anything in either the Snakefile or any of the files ending with .smk?

**Comment by anjanaanilkumar1289** [comment] 2019-01-29 12:18
Dear Johannes,

I didn't change the Snakefile and the rules. I am attaching the edited
config file herewith.

Regards,
Anjana

**Comment by johanneskoester** [comment] 2019-01-30 08:12
I cannot see the config (I guess email attachments are not included here). Maybe you can just post it inside a comment?

**Comment by anjanaanilkumar1289** [comment] 2019-01-30 09:02
Hi,
I have pasted the config file below.



#######################################################################

samples:
/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/samples.tsv
units:
/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/units.tsv


ref:
  # name used in snpeff database
  name: GRCh38
  genome: /data/Priyanka/breast_fastq/Reference/GRCh38.p12.genome.fa
  # known variants (e.g. DBSNP)
  known-variants: /data/anjana/data/clinvar_20190114.vcf


filtering:
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: false
  hard:
    # hard filtering as outlined in GATK docs
    # (
https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set
)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 ||
ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"

processing:
  remove-duplicates: false
  # point to a bed file with e.g. captured regions if necessary,
  # see
https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals
#  restrict-regions: ../raw/captured_regions.bed
  # If regions are restricted, use this to enlarge them in order to include
  # flanking areas.
#  region-padding: 100

params:
  gatk:
    HaplotypeCaller: ""
    BaseRecalibrator: ""
    GenotypeGVCFs: ""
    VariantRecalibrator: ""
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  trimmomatic:
    pe:
      trimmer:
        -
"ILLUMINACLIP:/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/test/TruSeq3-PE.fa"
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
    se:
      trimmer:
        -
"ILLUMINACLIP:/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/test/TruSeq3-SE.fa"
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"

#########################################################################################

**Comment by anjanaanilkumar1289** [comment] 2019-01-30 10:18
Hi,

Unfortunately I am not getting the TypeError anymore. But still there is an
error with trimmomatic that I am pasting here.

##############################################################################

Traceback (most recent call last):
  File
"/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/.snakemake/scripts/
tmpv2f735y6.wrapper.py", line 56, in <module>
    "trimmomatic PE {extra} "
  File
"/home/anjana/anaconda3/lib/python3.6/site-packages/snakemake/shell.py",
line 142, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' set -euo pipefail;  trimmomatic PE
-trimlog trimmed/A-1.trimlog.txt
/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/test/reads/a.chr21.1.fq
/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/test/reads/a.chr21.2.fq
>(pigz -5 > trimmed/A-1.1.fastq.gz) >(pigz -5 >
trimmed/A-1.1.unpaired.fastq.gz) >(pigz -5 > trimmed/A-1.2.fastq.gz) >(pigz
-5 > trimmed/A-1.2.unpaired.fastq.gz)
ILLUMINACLIP:/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/test/TruSeq3-PE.fa
LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36  >
logs/trimmomatic/A-1.log 2>&1 ' returned non-zero exit status 127.
/usr/bin/bash: fastqc: command not found
Traceback (most recent call last):
  File
"/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/.snakemake/scripts/
tmp3wrr9ead.wrapper.py", line 34, in <module>
    shell("fastqc {snakemake.params} --quiet "
  File
"/home/anjana/anaconda3/lib/python3.6/site-packages/snakemake/shell.py",
line 142, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' set -euo pipefail;  fastqc
--quiet --outdir /tmp/tmp4v5myicp
/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/test/reads/b.chr21.1.fq
' returned non-zero exit status 127.
Traceback (most recent call last):
  File
"/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/.snakemake/scripts/
tmpe88k4qc0.wrapper.py", line 56, in <module>
    "trimmomatic PE {extra} "
  File
"/home/anjana/anaconda3/lib/python3.6/site-packages/snakemake/shell.py",
line 142, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' set -euo pipefail;  trimmomatic PE
-trimlog trimmed/B-1.trimlog.txt
/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/test/reads/b.chr21.1.fq
/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/test/reads/b.chr21.2.fq
>(pigz -5 > trimmed/B-1.1.fastq.gz) >(pigz -5 >
trimmed/B-1.1.unpaired.fastq.gz) >(pigz -5 > trimmed/B-1.2.fastq.gz) >(pigz
-5 > trimmed/B-1.2.unpaired.fastq.gz)
ILLUMINACLIP:/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/test/TruSeq3-PE.fa
LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36  >
logs/trimmomatic/B-1.log 2>&1 ' returned non-zero exit status 127.

[Wed Jan 30 15:02:52 2019]
Error in rule trim_reads_pe:
    jobid: 25
    output: trimmed/A-1.1.fastq.gz, trimmed/A-1.2.fastq.gz,
trimmed/A-1.1.unpaired.fastq.gz, trimmed/A-1.2.unpaired.fastq.gz,
trimmed/A-1.trimlog.txt
    log: logs/trimmomatic/A-1.log

RuleException:
CalledProcessError in line 31 of
/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/rules/mapping.smk:
Command ' set -euo pipefail;  /home/anjana/anaconda3/bin/python
/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/.snakemake/scripts/
tmpv2f735y6.wrapper.py ' returned non-zero exit status 1.
  File
"/data/anjana/variant-calling/dna-seq-gatk-variant-calling-master/rules/mapping.smk",
line 31, in __rule_trim_reads_pe
  File "/home/anjana/anaconda3/lib/python3.6/concurrent/futures/thread.py",
line 56, in run
#################################################################################

Regards,
Anjana

**Comment by johanneskoester** [comment] 2019-01-30 10:20
You have to look into the log file. Did you run the pipeline with --use-conda?

**Comment by anjanaanilkumar1289** [comment] 2019-01-30 10:40
log file shows "*/usr/bin/bash: trimmomatic: command not found*"

I didn't run with --use-conda. I used -j .

**Comment by johanneskoester** [comment] 2019-01-30 10:43
That's the issue. You need --use-conda, in order to tell Snakemake to deploy the required software before running the workflow. Otherwise, you need to install all required tools manually. I strongly discourage the latter because it defeats reproducibility.

**Comment by johanneskoester** [comment] 2019-01-30 10:44
-j just tells Snakemake to use as many cores as possible, which is unrelated to the software deployment.

**Comment by anjanaanilkumar1289** [comment] 2019-01-30 10:45
Thank you so much!! I will try with --use-conda

**Comment by johanneskoester** [comment] 2019-01-30 11:01
Ok, I am therefore closing this for now.

**Closed by johanneskoester** 2019-01-30 11:01 UTC
